version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/spring-boot-example"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/jakarta-ee-example"
    schedule:
      interval: "weekly"
