name: Maven Build

on: [ push, pull_request ]

jobs:
  build-sample-projects:
    strategy:
      fail-fast: false
      matrix:
        projects: [ 'spring-boot-example', 'jakarta-ee-example' ]
    runs-on: ubuntu-20.04
    name: ${{ matrix.projects }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0
          distribution: 'adopt'
          java-package: 'jdk'

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.projects }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.projects }}-

      - name: Build the project
        working-directory: ${{ matrix.projects }}
        run: ./mvnw -B verify

      - name: Log test output on failure
        if: failure() || cancelled()
        run: find . -type f -path "*test-reports/*-output.txt" -exec tail -n +1 {} +

  run-gatling-performance-tests:
    runs-on: ubuntu-20.04
    name: gatling-example
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0
          distribution: 'adopt'
          java-package: 'jdk'

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-gatling-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-gatling-

      - name: Run the load tests
        run: |
          docker-compose --file spring-boot-example/docker-compose.yml up -d
          mvn --file spring-boot-example/pom.xml -B spring-boot:run &
          mvn --file spring-boot-example/pom.xml -B gatling:test
